// Generated by CoffeeScript 1.6.3
(function() {
  var $, DISP_EMPTY, DISP_PLANT, WORLD_HEIGHT, WORLD_WIDTH, add_plants, draw_world, plants, random_int, skip_day, update_world, world;

  WORLD_WIDTH = 100;

  WORLD_HEIGHT = 30;

  DISP_EMPTY = ".";

  DISP_PLANT = "*";

  world = [];

  plants = [];

  $ = function(id) {
    return document.getElementById(id);
  };

  skip_day = function() {
    console.log("skip day");
    update_world();
    return draw_world();
  };

  update_world = function() {
    return add_plants();
  };

  draw_world = function() {
    var ary, x, y, _i, _j;
    ary = [];
    for (y = _i = 0; 0 <= WORLD_HEIGHT ? _i < WORLD_HEIGHT : _i > WORLD_HEIGHT; y = 0 <= WORLD_HEIGHT ? ++_i : --_i) {
      for (x = _j = 0; 0 <= WORLD_WIDTH ? _j < WORLD_WIDTH : _j > WORLD_WIDTH; x = 0 <= WORLD_WIDTH ? ++_j : --_j) {
        switch (world[[x, y]]) {
          case "plant":
            ary.push(DISP_PLANT);
            break;
          default:
            ary.push(DISP_EMPTY);
        }
      }
      ary.push("\n");
    }
    return $("world").innerHTML = ary.join('');
  };

  random_int = function(min, max) {
    return min + Math.floor(Math.random() * max);
  };

  add_plants = function() {
    var pos;
    pos = {
      x: random_int(0, WORLD_WIDTH),
      y: random_int(0, WORLD_HEIGHT)
    };
    return world[[pos.x, pos.y]] = "plant";
  };

  window.onload = function() {
    console.log("loaded");
    draw_world();
    return $("simulate_btn").addEventListener("click", skip_day);
  };

}).call(this);
