// Generated by CoffeeScript 1.6.3
(function() {
  var $, Animal, DISP_ANIMAL, DISP_EMPTY, DISP_PLANT, JUNGLE, WORLD_HEIGHT, WORLD_WIDTH, add_plants, animals, dist_x_by_dir, dist_y_by_dir, draw_world, plants, random_int, skip_day, update_world, world;

  WORLD_WIDTH = 100;

  WORLD_HEIGHT = 30;

  JUNGLE = {
    x: 45,
    y: 10,
    width: 10,
    height: 10
  };

  DISP_EMPTY = " ";

  DISP_PLANT = "*";

  DISP_ANIMAL = "M";

  world = [];

  plants = [];

  animals = [];

  $ = function(id) {
    return document.getElementById(id);
  };

  skip_day = function() {
    console.log("skip day");
    update_world();
    return draw_world();
  };

  update_world = function() {
    var animal, _i, _len, _results;
    add_plants();
    _results = [];
    for (_i = 0, _len = animals.length; _i < _len; _i++) {
      animal = animals[_i];
      _results.push(animal.move());
    }
    return _results;
  };

  draw_world = function() {
    var animal, ary, x, y, _i, _j, _k, _l, _len, _m;
    world = [];
    for (y = _i = 0; 0 <= WORLD_HEIGHT ? _i < WORLD_HEIGHT : _i > WORLD_HEIGHT; y = 0 <= WORLD_HEIGHT ? ++_i : --_i) {
      for (x = _j = 0; 0 <= WORLD_WIDTH ? _j < WORLD_WIDTH : _j > WORLD_WIDTH; x = 0 <= WORLD_WIDTH ? ++_j : --_j) {
        if (plants[[x, y]]) {
          world[[x, y]] = "plant";
        }
      }
    }
    for (_k = 0, _len = animals.length; _k < _len; _k++) {
      animal = animals[_k];
      world[[animal.x, animal.y]] = "animal";
    }
    ary = [];
    for (y = _l = 0; 0 <= WORLD_HEIGHT ? _l < WORLD_HEIGHT : _l > WORLD_HEIGHT; y = 0 <= WORLD_HEIGHT ? ++_l : --_l) {
      for (x = _m = 0; 0 <= WORLD_WIDTH ? _m < WORLD_WIDTH : _m > WORLD_WIDTH; x = 0 <= WORLD_WIDTH ? ++_m : --_m) {
        switch (world[[x, y]]) {
          case "animal":
            ary.push(DISP_ANIMAL);
            break;
          case "plant":
            ary.push(DISP_PLANT);
            break;
          default:
            ary.push(DISP_EMPTY);
        }
      }
      ary.push("\n");
    }
    return $("world").innerHTML = ary.join('');
  };

  random_int = function(min, max) {
    return min + Math.floor(Math.random() * max);
  };

  add_plants = function() {
    var pos;
    pos = {
      x: random_int(0, WORLD_WIDTH),
      y: random_int(0, WORLD_HEIGHT)
    };
    plants[[pos.x, pos.y]] = true;
    pos = {
      x: random_int(JUNGLE.x, JUNGLE.width),
      y: random_int(JUNGLE.y, JUNGLE.height)
    };
    return plants[[pos.x, pos.y]] = true;
  };

  dist_x_by_dir = {
    0: -1,
    1: 0,
    2: 1,
    3: 1,
    4: 1,
    5: 0,
    6: -1,
    7: -1
  };

  dist_y_by_dir = {
    0: -1,
    1: -1,
    2: -1,
    3: 0,
    4: 1,
    5: 1,
    6: 1,
    7: 0
  };

  Animal = (function() {
    function Animal(x, y, direction) {
      this.x = x;
      this.y = y;
      this.direction = direction;
    }

    Animal.prototype.move = function() {
      this.x += dist_x_by_dir[this.direction];
      this.y += dist_y_by_dir[this.direction];
      if (this.x < 0) {
        this.x += WORLD_WIDTH;
      }
      if (WORLD_WIDTH <= this.x) {
        this.x -= WORLD_WIDTH;
      }
      if (this.y < 0) {
        this.y += WORLD_HEIGHT;
      }
      if (WORLD_HEIGHT <= this.y) {
        return this.y -= WORLD_HEIGHT;
      }
    };

    return Animal;

  })();

  window.onload = function() {
    console.log("loaded");
    animals.push(new Animal(50, 15, 0));
    draw_world();
    return $("simulate_btn").addEventListener("click", skip_day);
  };

}).call(this);
